# Generated by Django 5.1.3 on 2024-11-22 13:41

import django.db.models.deletion
import spy_cat_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpyCat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("years_of_experience", models.IntegerField()),
                (
                    "breed",
                    models.CharField(
                        max_length=100,
                        validators=[spy_cat_app.validators.validate_breed],
                    ),
                ),
                ("salary", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete_state", models.BooleanField(default=False)),
                (
                    "cat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spy_cat_app.spycat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                ("complete_state", models.BooleanField(default=False)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="spy_cat_app.mission",
                    ),
                ),
            ],
        ),
    ]
